# Project Configuration

# Target States
target_states:
  - MS  # Mississippi
  - AL  # Alabama

# Data Sources
data_sources:
  igs:
    portal: "https://inclusivegrowthscore.com/market/us/"
  acs:
    api_base: "https://api.census.gov/data"
    dataset: "acs/acs5"
    variables:
      insurance: "B27020"
      gini: "B19083_001E"
      income: "B19013_001E"
      poverty: "B17001"
  facilities:
    hospitals: "CMS Hospital General Information"
    clinics: "HRSA Health Center Locations"
    pharmacies: "CMS Part D or NCPDP"
  geography:
    tracts: "Census TIGER/Line"

# Model Parameters
model:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  
  # Health Desert thresholds (0-100)
  desert_thresholds:
    extreme: 76
    high: 51
    moderate: 26
    low: 0

# Visualization Settings
visualization:
  map_center:
    lat: 30.0
    lon: -90.0
  map_zoom: 5
  
  color_scales:
    desert: "Reds"
    igs: "Blues"

# Output Paths
paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  data_external: "data/external"
  models: "models"
  logs: "logs"

