# Project Configuration

# Target States
target_states:
  - FL  # Florida
  - MS  # Mississippi
  - LA  # Louisiana
  - TX  # Texas
  - AL  # Alabama

# Data Sources
data_sources:
  noaa_storm_events:
    url: "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/"
    start_year: 1950
    end_year: 2025
  
  fema_declarations:
    api_base: "https://www.fema.gov/api/open/v2"
    endpoint: "/DisasterDeclarationsSummaries"
  
  cdc_svi:
    url: "https://www.atsdr.cdc.gov/placeandhealth/svi/data_documentation_download.html"
    year: 2020
  
  billion_dollar_disasters:
    url: "https://www.ncei.noaa.gov/access/billions/"

# Model Parameters
model:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  
  # Risk classification thresholds
  risk_thresholds:
    high: 0.75
    medium: 0.50
    low: 0.25

# Visualization Settings
visualization:
  map_center:
    lat: 30.0
    lon: -90.0
  map_zoom: 5
  
  color_scales:
    risk: "RdYlGn_r"
    igs: "Blues"
    svi: "Reds"

# Output Paths
paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  data_external: "data/external"
  models: "models"
  logs: "logs"

